name: project19
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.2.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.3
  app_tracking_transparency: ^2.0.4
  flutter_inappwebview: ^5.8.0
  appsflyer_sdk: 
  overlay_support: ^2.1.0
  hive_flutter: ^1.1.0
  fl_chart: ^0.69.0
  url_launcher:
  # dio: ^5.6.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    # SF-UI-Display
    - family: SFR
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-UI-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-UI-Display-Bold.ttf
    # Mulish
    - family: MulishR
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: MulishM
      fonts:
        - asset: assets/fonts/Mulish-Medium.ttf
    - family: MulishB
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
    # Inter
    - family: InterR
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterM
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterB
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf